name: auto_pass_manager
channels:
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.16.1=py_0
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - jdcal=1.4.1=py_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcxx=9.0.0=h89e68fa_1
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h4bb4525_3
  - llvm-openmp=9.0.0=h40edb58_0
  - macholib=1.11=py_0
  - ncurses=6.1=h0a44026_1002
  - numpy=1.17.3=py37hde6bac1_0
  - openssl=1.1.1d=h0b31af3_0
  - pip=19.3.1=py37_0
  - pycrypto=2.6.1=py37h0b31af3_1003
  - pyinstaller=3.5=py37ha441bb4_0
  - python=3.7.3=h93065d6_1
  - readline=8.0=hcfe32e1_0
  - scipy=1.3.2=py37h82752d6_0
  - setuptools=41.6.0=py37_1
  - sqlite=3.30.1=h93121df_0
  - tk=8.6.9=h2573ce8_1003
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_1001
  - zlib=1.2.11=h0b31af3_1006
prefix: /Users/jmason86/anaconda3/envs/auto_pass_manager

